### ISSUE TITLE
Fix VoteOut pop up window

### ISSUE THREAD

**Issue by EmilyLangenfeld** [yhz3/werewolf#41]
After a player name is entered to be voted out, a pop up window displaying a ChatGPT story is supposed to appear on the screen. Right now, a pop up window appears on the screen after clicking 'Vote Out', but the pop up window is blank instead of displaying the ChatGPT story. We need to fix the VoteOut interface adapters, so that the pop up will display the story.

**Comment by yunfeikevinwang** [comment]
Fixed. Added story response after voting out player. Switches view to kill player
