### ISSUE TITLE
Bug: Program switches view even though player is not part of the game anymore

### ISSUE THREAD

**Issue by EmilyLangenfeld** [yhz3/werewolf#63]
When a villager is killed or a player is voted out, that either does not exist or is not part of the game anymore, the program switches view. However, it should stay at the same view and make the game master re-enter a new player to be voted out.

**Comment by daniyaalf** [comment]
This bug should be fixed after my pull request fixing bugs with the new game UI since I adjusted some of the others (see that pull request)
